version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.confi
    networks:
      - nginx-network

  python-app:
    build:
      dockerfile: Python/Dockerfile
    container_name: python_app
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
    # options:
    #   complex_option: value
